version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      TZ: Asia/Tokyo
    command: mysqld
    ports:
      - '3306:3306'
    volumes:
#      - ./docker/mysql/init:/docker-entrypoint-initdb.d # 初期データ
      - db_volume:/var/lib/mysql                        # 永続化

#  spring:
#    build: ./docker/springboot/
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./build/libs:/app/lib
#    depends_on:
#      - db

volumes:
  db_volume: