version: '3'

services:

  db:
    image: oracle/database:18.4.0-xe
    container_name: oracle18c
    ports:
      - 1521:1521
    volumes:
      - db-volume:/opt/oracle/oradata
      - ./docker/db/scripts/startup:/opt/oracle/scripts/startup
      - ./docker/db/scripts/setup:/opt/oracle/scripts/setup
    environment:
      - ORACLE_PWD=passw0rd
      - NLS_LANG=Japanese_Japan.AL32UTF8

volumes:
  db-volume: