-- PDBへ切り替え
ALTER SESSION SET CONTAINER=pdb01;

-- ユーザ削除
DROP USER SpringBoot CASCADE;

-- ユーザ作成
CREATE USER SpringBoot IDENTIFIED BY SpringBoot
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp;

-- 作成ユーザへ権限付与
GRANT CREATE SESSION TO SpringBoot;
GRANT RESOURCE TO SpringBoot;
GRANT UNLIMITED TABLESPACE TO SpringBoot;